# Análisis estadístico

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [2]:
df_final = pd.read_csv('files/df_final_limpio.csv', index_col = 0)
df_final.info()

<class 'pandas.DataFrame'>
Index: 405624 entries, 100018 to 999986
Data columns (total 25 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   year                         405624 non-null  int64
 1   date                         405624 non-null  str
 2   flights_booked               405624 non-null  int64
 3   flights_with_companions      405624 non-null  int64
 4   total_flights                405624 non-null  int64
 5   distance                     405624 non-null  int64
 6   points_accumulated           405624 non-null  float64
 7   points_redeemed              405624 non-null  int64
 8   dollar_cost_points_redeemed  405624 non-null  int64
 9   country                      405624 non-null  str
 10  province                     405624 non-null  str
 11  city                         405624 non-null  str
 12  postal_code                  405624 non-null  str
 13  gender                       405624 non-null  str
 14  education                    405624 non-null  str
 15  salary                       405624 non-null  float64
 16  marital_status               405624 non-null  str
 17  loyalty_card                 405624 non-null  str
 18  clv                          405624 non-null  float64
 19  enrollment_type              405624 non-null  str
 20  enrollment_date              405624 non-null  str
 21  enrollment_year              405624 non-null  int64
 22  cancellation_year            50064 non-null   float64
 23  cancellation_date            50064 non-null   str
 24  is_cancelled                 405624 non-null  bool
dtypes: bool(1), float64(4), int64(8), str(12)
memory usage: 77.8 MB

## Variables numéricas

In [3]:
df_final.describe().T

,count,mean,std,min,25%,50%,75%,max
year,405624.0,2017.500000,0.500001,2017.00,2017.00,2017.50,2018.00,2018.00
flights_booked,405624.0,4.115052,5.225518,0.00,0.00,1.00,8.00,21.00
flights_with_companions,405624.0,1.031805,2.076869,0.00,0.00,0.00,1.00,11.00
total_flights,405624.0,5.146858,6.521227,0.00,0.00,1.00,10.00,32.00
distance,405624.0,1208.880059,1433.155320,0.00,0.00,488.00,2336.00,6293.00
points_accumulated,405624.0,123.692721,146.599831,0.00,0.00,50.00,239.00,676.50
points_redeemed,405624.0,30.696872,125.486049,0.00,0.00,0.00,0.00,876.00
dollar_cost_points_redeemed,405624.0,2.484503,10.150038,0.00,0.00,0.00,0.00,71.00
salary,405624.0,79658.027632,32152.011843,15609.00,61431.00,73943.00,87818.00,407228.00
clv,405624.0,7991.976226,6863.663857,1898.01,3985.32,5776.34,8936.82,83325.38
enrollment_year,405624.0,2015.252529,1.979427,2012.00,2014.00,2015.00,2017.00,2018.00
cancellation_year,50064.0,2016.499521,1.384336,2013.00,2016.00,2017.00,2018.00,2018.00

In [20]:
# Función para sacar el análisis estadístico de cada variable por separado

def resumen_variable(df, columna):

    serie_original = df[columna]
    serie = serie_original.dropna()

    media = serie.mean()
    mediana = serie.median()
    moda = serie.mode()
    desviacion = serie.std()
    minimo = serie.min()
    maximo = serie.max()
    varianza = serie.var()
    q1 = serie.quantile(0.25)
    q3 = serie.quantile(0.75)
    rango_intercuartilico = q3 - q1
    rango = maximo - minimo

    if media != 0:
        coef_variacion = (desviacion / media)*100
    else:
        coef_variacion = np.nan

    resumen = pd.DataFrame({
        "variable": [columna],
        "media": [round(media, 2)],
        "mediana": [round(mediana, 2)],
        "moda": [moda.iloc[0] if len(moda) > 0 else np.nan],
        "desviacion_estandar": [round(desviacion, 2)],
        "minimo": [round(minimo, 2)],
        "maximo": [round(maximo, 2)],
        "varianza": [round(varianza, 2)],
        "q1": [round(q1, 2)],
        "q3": [round(q3, 2)],
        "rango_intercuartilico": [round(rango_intercuartilico, 2)],
        "rango": [round(rango, 2)],
        "coeficiente_variacion": [round(coef_variacion, 2)]
    }).T

    return resumen

In [21]:
resumen_variable(df_final, 'flights_booked')

                                    0
variable               flights_booked
media                            4.12
mediana                           1.0
moda                                0
desviacion_estandar              5.23
minimo                              0
maximo                             21
varianza                        27.31
q1                                0.0
q3                                8.0
rango_intercuartilico             8.0
rango                              21
coeficiente_variacion          126.99

Análisis:
- La distancia entre la media y la mediana indican que puede que haya pocas personas que viajan mucho, frente a una mayoría que viaja poco.
- Esta hipótesis se refuerza porque el número más repetido de viajes reservados es 0.
- La varianza y la desviación estándar también indican esta dispersión en los datos
- El 50% de los datos se sitúa entre los 0 y los 8 viajes reservados.

In [22]:
resumen_variable(df_final, 'flights_with_companions')

                                             0
variable               flights_with_companions
media                                     1.03
mediana                                    0.0
moda                                         0
desviacion_estandar                       2.08
minimo                                       0
maximo                                      11
varianza                                  4.31
q1                                         0.0
q3                                         1.0
rango_intercuartilico                      1.0
rango                                       11
coeficiente_variacion                   201.29

Análisis:
- En este caso, apenas hay distancia entre la media y la mediana. Y la mediana es igual que la moda.
- Por tanto, el número de acompañantes más repetidos es 0, y al menos el 50% de los viajes han sido sin acompañante
- El máximo de vuelos con acompañante ha sido 11

In [23]:
resumen_variable(df_final, 'total_flights')

                                   0
variable               total_flights
media                           5.15
mediana                          1.0
moda                               0
desviacion_estandar             6.52
minimo                             0
maximo                            32
varianza                       42.53
q1                               0.0
q3                              10.0
rango_intercuartilico           10.0
rango                             32
coeficiente_variacion          126.7

Análisis:

- Al igual que en las anteriores, vemos una media y una mediana alejadas, con un muy alto coeficiente de variación, lo que indica que hay una polarización extrema, con la mayoría de clientes dormidos y unos pocos con mucha actividad que inflan la media y que presenta una asimetría pronunciada hacia la derecha

In [24]:
resumen_variable(df_final, 'distance')

                                0
variable                 distance
media                     1208.88
mediana                     488.0
moda                            0
desviacion_estandar       1433.16
minimo                          0
maximo                       6293
varianza               2053934.17
q1                            0.0
q3                         2336.0
rango_intercuartilico      2336.0
rango                        6293
coeficiente_variacion      118.55

Análisis:
- La media es bastante superior a la mediana, lo que indica una distribución asimétrica hacia la derecha
- Como en los casos anteriores el número de vuelos/mes más repetido era 0, tiene sentido que la distancia más repetida sea 0.
- Esto explica, a su vez, esta gran diferencia entre la media, la moda y la mediana, ya que las distancias en avión son muy grandes y, aunque se hagan pocos vuelos, esto ya aumentaría mucho la diferencia entre los valores.
- Por tanto, la desviación con respecto a la media es también muy alta, lo que va a derivar en una alta dispersión de los datos.

In [25]:
resumen_variable(df_final, 'points_accumulated')

                                        0
variable               points_accumulated
media                              123.69
mediana                              50.0
moda                                  0.0
desviacion_estandar                 146.6
minimo                                0.0
maximo                              676.5
varianza                         21491.51
q1                                    0.0
q3                                  239.0
rango_intercuartilico               239.0
rango                               676.5
coeficiente_variacion              118.52

Análisis:
- Toda la tabla está marcada por que hay muchos meses que muchos clientes no realizan vuelos.
- Partiendo de esa base, se sigue explicando que haya tanta distancia entre la media y la mediana, lo que indica que hay valores extremos. Reforzado por que la el valor más repetido en este caso también es 0
- Los datos por tanto no están concentrados ni son simétricos

In [26]:
resumen_variable(df_final, 'points_redeemed')

                                     0
variable               points_redeemed
media                             30.7
mediana                            0.0
moda                                 0
desviacion_estandar             125.49
minimo                               0
maximo                             876
varianza                      15746.75
q1                                 0.0
q3                                 0.0
rango_intercuartilico              0.0
rango                              876
coeficiente_variacion           408.79

Análisis:
- Dado que los puntos redimidos están condicionados por los vuelos, los datos presentan un comportamiento similar, con una media y una moda igual a 0, pero con una media de 30,7, claramente distorsionada por los pocos clientes que más viajan. Lo que a su vez explica la dispersión de los datos y la asimetría de su distribución, que reflejan tanto la desviación estándar como el coeficiente de variación.

In [27]:
resumen_variable(df_final, 'dollar_cost_points_redeemed')

                                                 0
variable               dollar_cost_points_redeemed
media                                         2.48
mediana                                        0.0
moda                                             0
desviacion_estandar                          10.15
minimo                                           0
maximo                                          71
varianza                                    103.02
q1                                             0.0
q3                                             0.0
rango_intercuartilico                          0.0
rango                                           71
coeficiente_variacion                       408.53

Análisis:

- En el coste en dólares de los puntos redimidos vemos también un comportamiento similar en los datos, con un coeficiente de variación muy alto que llama especialmente la atención y que demuestra una polarización extrema.

##### Cálculo estadísticas salario y clv

Para calcular las estadísticas de salario y clv, es más correcto usar una tabla que elimine los duplicados de los clientes, para que no haya distorsiones en los datos. Por ello, creamos otra tabla en la que 'loyalty_number' aparezca solo una vez.

In [28]:
df_final = df_final.reset_index()

In [29]:
df_final.head()
df_final.columns

Index(['index', 'Loyalty Number', 'year', 'date', 'flights_booked',
       'flights_with_companions', 'total_flights', 'distance',
       'points_accumulated', 'points_redeemed', 'dollar_cost_points_redeemed',
       'country', 'province', 'city', 'postal_code', 'gender', 'education',
       'salary', 'marital_status', 'loyalty_card', 'clv', 'enrollment_type',
       'enrollment_date', 'enrollment_year', 'cancellation_year',
       'cancellation_date', 'is_cancelled'],
      dtype='str')

In [30]:
df_clientes = df_final.drop_duplicates(subset="Loyalty Number")

In [31]:


resumen_variable(df_clientes, 'salary')

                                   0
variable                      salary
media                       79651.92
mediana                      73943.0
moda                        118373.4
desviacion_estandar         32166.78
minimo                       15609.0
maximo                      407228.0
varianza               1034702011.98
q1                           61413.4
q3                           87799.0
rango_intercuartilico        26385.6
rango                       391619.0
coeficiente_variacion          40.38

In [34]:
resumen_variable(df_clientes, 'clv')

                                 0
variable                       clv
media                       7988.9
mediana                    5780.18
moda                       8564.77
desviacion_estandar        6860.98
minimo                     1898.01
maximo                    83325.38
varianza               47073077.85
q1                         3980.84
q3                         8940.58
rango_intercuartilico      4959.74
rango                     81427.37
coeficiente_variacion        85.88