# Limpieza y transformación de datos

### CSV Customer Flight Activity

In [8]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [9]:
df_activity = pd.read_csv('files/Customer flight Activity.csv', index_col = 0)
df_activity.head()

,Year,Month,Flights Booked,Flights with Companions,Total Flights,Distance,Points Accumulated,Points Redeemed,Dollar Cost Points Redeemed
Loyalty Number,,,,,,,,,
100018,2017,1,3,0,3,1521,152.0,0,0
100102,2017,1,10,4,14,2030,203.0,0,0
100140,2017,1,6,0,6,1200,120.0,0,0
100214,2017,1,0,0,0,0,0.0,0,0
100272,2017,1,0,0,0,0,0.0,0,0

In [21]:
# unir columnas year-month

df_activity["date"] = pd.to_datetime(
    df_activity["Year"].astype(str) + "-" + df_activity["Month"].astype(str) + "-01"
)

In [30]:
columna = df_activity.pop("date")

In [31]:

df_activity.insert(2, "date", columna)

In [ ]:
#Elimino columna Month
df_activity = df_activity.drop(columns="Month")

In [38]:
df_activity[df_activity.duplicated()]

,Year,date,Flights Booked,Flights with Companions,Total Flights,Distance,Points Accumulated,Points Redeemed,Dollar Cost Points Redeemed
Loyalty Number,,,,,,,,,
100272,2017,2017-01-01,0,0,0,0,0.0,0,0
100301,2017,2017-01-01,0,0,0,0,0.0,0,0
100364,2017,2017-01-01,0,0,0,0,0.0,0,0
100380,2017,2017-01-01,0,0,0,0,0.0,0,0
100504,2017,2017-01-01,0,0,0,0,0.0,0,0
...,...,...,...,...,...,...,...,...,...
999891,2018,2018-12-01,0,0,0,0,0.0,0,0
999902,2018,2018-12-01,0,0,0,0,0.0,0,0
999911,2018,2018-12-01,0,0,0,0,0.0,0,0
999982,2018,2018-12-01,0,0,0,0,0.0,0,0
999986,2018,2018-12-01,0,0,0,0,0.0,0,0

In [35]:
df_activity

,Year,date,Flights Booked,Flights with Companions,Total Flights,Distance,Points Accumulated,Points Redeemed,Dollar Cost Points Redeemed
Loyalty Number,,,,,,,,,
100018,2017,2017-01-01,3,0,3,1521,152.0,0,0
100102,2017,2017-01-01,10,4,14,2030,203.0,0,0
100140,2017,2017-01-01,6,0,6,1200,120.0,0,0
100214,2017,2017-01-01,0,0,0,0,0.0,0,0
100272,2017,2017-01-01,0,0,0,0,0.0,0,0
...,...,...,...,...,...,...,...,...,...
999902,2018,2018-12-01,0,0,0,0,0.0,0,0
999911,2018,2018-12-01,0,0,0,0,0.0,0,0
999940,2018,2018-12-01,3,0,3,1233,123.0,0,0
999982,2018,2018-12-01,0,0,0,0,0.0,0,0
999986,2018,2018-12-01,0,0,0,0,0.0,0,0

In [39]:
df_activity.isnull().sum() / len(df_activity) * 100

Year                           0.0
date                           0.0
Flights Booked                 0.0
Flights with Companions        0.0
Total Flights                  0.0
Distance                       0.0
Points Accumulated             0.0
Points Redeemed                0.0
Dollar Cost Points Redeemed    0.0
dtype: float64

In [23]:
df_activity.info()

<class 'pandas.DataFrame'>
Index: 405624 entries, 100018 to 999986
Data columns (total 10 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Year                         405624 non-null  int64
 1   Month                        405624 non-null  int64
 2   Flights Booked               405624 non-null  int64
 3   Flights with Companions      405624 non-null  int64
 4   Total Flights                405624 non-null  int64
 5   Distance                     405624 non-null  int64
 6   Points Accumulated           405624 non-null  float64
 7   Points Redeemed              405624 non-null  int64
 8   Dollar Cost Points Redeemed  405624 non-null  int64
 9   date                         405624 non-null  datetime64[us]
dtypes: datetime64[us](1), float64(1), int64(8)
memory usage: 34.0 MB

### CSV customer loyalty history

In [10]:
df_loyalty = pd.read_csv('files/Customer Loyalty History.csv', index_col = 0)
df_loyalty.head()

,Country,Province,City,Postal Code,Gender,Education,Salary,Marital Status,Loyalty Card,CLV,Enrollment Type,Enrollment Year,Enrollment Month,Cancellation Year,Cancellation Month
Loyalty Number,,,,,,,,,,,,,,,
480934,Canada,Ontario,Toronto,M2Z 4K1,Female,Bachelor,83236.0,Married,Star,3839.14,Standard,2016,2,NaN,NaN
549612,Canada,Alberta,Edmonton,T3G 6Y6,Male,College,NaN,Divorced,Star,3839.61,Standard,2016,3,NaN,NaN
429460,Canada,British Columbia,Vancouver,V6E 3D9,Male,College,NaN,Single,Star,3839.75,Standard,2014,7,2018.0,1.0
608370,Canada,Ontario,Toronto,P1W 1K4,Male,College,NaN,Single,Star,3839.75,Standard,2013,2,NaN,NaN
530508,Canada,Quebec,Hull,J8Y 3Z5,Male,Bachelor,103495.0,Married,Star,3842.79,Standard,2014,10,NaN,NaN

In [12]:
df_loyalty.info()

<class 'pandas.DataFrame'>
Index: 16737 entries, 480934 to 652627
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Country             16737 non-null  str
 1   Province            16737 non-null  str
 2   City                16737 non-null  str
 3   Postal Code         16737 non-null  str
 4   Gender              16737 non-null  str
 5   Education           16737 non-null  str
 6   Salary              12499 non-null  float64
 7   Marital Status      16737 non-null  str
 8   Loyalty Card        16737 non-null  str
 9   CLV                 16737 non-null  float64
 10  Enrollment Type     16737 non-null  str
 11  Enrollment Year     16737 non-null  int64
 12  Enrollment Month    16737 non-null  int64
 13  Cancellation Year   2067 non-null   float64
 14  Cancellation Month  2067 non-null   float64
dtypes: float64(4), int64(2), str(9)
memory usage: 2.0 MB

In [ ]:
#Comprobación de duplicados
df_loyalty.duplicated().sum()

np.int64(0)

In [52]:
# unir columnas enrollment year-month

df_loyalty["Enrollment Date"] = pd.to_datetime(
    df_loyalty["Enrollment Year"].astype(str) + "-" + df_loyalty["Enrollment Month"].astype(str) + "-01"
)

In [53]:
columna2 = df_loyalty.pop("Enrollment Date")
df_loyalty.insert(11, "Enrollment Date", columna2)

In [56]:
# unir columnas cancellation year-month

#primero las pasamos a int
columnas_cancellation = ['Cancellation Year', 'Cancellation Month']
df_loyalty[columnas_cancellation] = df_loyalty[columnas_cancellation].astype("Int64")

df_loyalty["Cancellation Date"] = pd.to_datetime(
    df_loyalty["Cancellation Year"].astype(str) + "-" + df_loyalty["Cancellation Month"].astype(str) + "-01"
)

In [58]:
#eliminar las columnas month

df_loyalty = df_loyalty.drop(columns=["Enrollment Month",'Cancellation Month'])

In [59]:
df_loyalty

,Country,Province,City,Postal Code,Gender,Education,Salary,Marital Status,Loyalty Card,CLV,Enrollment Type,Enrollment Date,Enrollment Year,Cancellation Year,Cancellation Date
Loyalty Number,,,,,,,,,,,,,,,
480934,Canada,Ontario,Toronto,M2Z 4K1,Female,Bachelor,83236.0,Married,Star,3839.14,Standard,2016-02-01,2016,<NA>,NaT
549612,Canada,Alberta,Edmonton,T3G 6Y6,Male,College,NaN,Divorced,Star,3839.61,Standard,2016-03-01,2016,<NA>,NaT
429460,Canada,British Columbia,Vancouver,V6E 3D9,Male,College,NaN,Single,Star,3839.75,Standard,2014-07-01,2014,2018,2018-01-01
608370,Canada,Ontario,Toronto,P1W 1K4,Male,College,NaN,Single,Star,3839.75,Standard,2013-02-01,2013,<NA>,NaT
530508,Canada,Quebec,Hull,J8Y 3Z5,Male,Bachelor,103495.0,Married,Star,3842.79,Standard,2014-10-01,2014,<NA>,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
823768,Canada,British Columbia,Vancouver,V6E 3Z3,Female,College,NaN,Married,Star,61850.19,Standard,2012-12-01,2012,<NA>,NaT
680886,Canada,Saskatchewan,Regina,S1J 3C5,Female,Bachelor,89210.0,Married,Star,67907.27,Standard,2014-09-01,2014,<NA>,NaT
776187,Canada,British Columbia,Vancouver,V5R 1W3,Male,College,NaN,Single,Star,74228.52,Standard,2014-03-01,2014,<NA>,NaT
906428,Canada,Yukon,Whitehorse,Y2K 6R0,Male,Bachelor,-57297.0,Married,Star,10018.66,2018 Promotion,2018-04-01,2018,<NA>,NaT
652627,Canada,Manitoba,Winnipeg,R2C 0M5,Female,Bachelor,75049.0,Married,Star,83325.38,Standard,2015-12-01,2015,2016,2016-08-01